[cursor.style]
blinking = "On"

[font]
builtin_box_drawing = false
size = 11.0

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 0.85
option_as_alt = "None"

[window.dimensions]
columns = 185
lines = 45

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "T", mods = "Control|Shift", action = "CreateNewTab" },
{ key = "T", mods = "Control|Shift", action = "SelectNextTab" },
{ key = "T", mods = "Control|Shift", action = "SelectPreviousTab" },
{ key = "K", mods = "Control|Shift", action = "ClearHistory" },
{ key = "K", mods = "Control|Shift", chars = "\u000c" },
]

[[hints.enabled]]
binding = { key = "O", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

# Default colors
[colors.primary]
# background = '#282828'
# hard contrast
background = '#1d2021'
# soft contrast
# background = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
