[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_title = true
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 0.97
decorations_theme_variant = "Dark"
option_as_alt = "None"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 100000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

# # cachyos colors {{{
# [colors.primary]
# background = "0x2E3440"
# foreground = "0xD8DEE9"

# [colors.normal]
# black = "0x3B4252"
# red = "0xBF616A"
# green = "0xA3BE8C"
# yellow = "0xEBCB8B"
# blue = "0x81A1C1"
# magenta = "0xB48EAD"
# cyan = "0x88C0D0"
# white = "0xE5E9F0"

# [colors.bright]
# black = "0x4C566A"
# red = "0xBF616A"
# green = "0xA3BE8C"
# yellow = "0xEBCB8B"
# blue = "0x81A1C1"
# magenta = "0xB48EAD"
# cyan = "0x8FBCBB"
# white = "0xECEFF4"
# # }}} cachyos colors

# {{{ gruvbox colors
[colors.primary]
# background = '#282828'
# hard contrast
background = '#1d2021'
# soft contrast
# background = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
# }}} gruvbox

[font]
builtin_box_drawing = false
size = 11

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[hints.enabled]]
binding = { key = "O", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
